### ISSUE TITLE
Final Issues for latest version of personal portfolio

### ISSUE THREAD

**Issue by bahim22** [bahim22/react-form#9]
### Info from previous issues

#7 Chrome dev tools feedback
#8 Fixes for dev branch

### Additional Info for rxt-ecrive and react-boiler repos
[React Template/Boilerplate Repo](https://github.com/bahim22/react-ded-boiler)
[React Business Landing Page](https://github.com/bahim22/rxt-ecrive)

### ToDo List for optimization and finishing touches

- [ ] Add Tests
- [x] Fix Asset sizing and optimize
- [x] Add unique project descriptions and remove test components
- [ ] Create a Full Doc How-To from all the info learned updating repo
- [x] Deploy to **Azure** and **Netlify** to compare
- [ ] Lazy Load components
- [ ] Refactor a dev branch for **react-ded-boiler**
- [ ] Refactor a prod branch w/ new UI for **rxt-ecrive**

#### Form Addition + Options

1. [x] Microsoft 365 and Google review Forms (add in addition to below options
2. [x] Formik/Formspree
3. [ ] Nodemailer with Express Backend

**Comment by bahim22** [comment]
![bundleStats](https://user-images.githubusercontent.com/78245175/171441548-9abe7029-89f5-43d5-b221-8cbd3e7512cc.jpeg)

**Comment by bahim22** [comment]
# Remaining and New to-do 

## 6 tasks left from pre Tech job

> 
- finish refactor for evrivé and react boiler
- Update GCP ref, and footer 


- [ ] refactor 
- [ ] Clean up and simplify

**Comment by bahim22** [comment]
Project was successfully deployed with 90+ lighthouse scoring and planned functionality. Stopped working on it due to new job and learning other skills. Will begin adjustments and make changes to the other 2 react projects and 2 nextJS projects.

**Comment by mariusgherasie** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
safronizator, @sumonst21, @ianpetrarca, @francofabio, @sailor95, @ryan1000, @zaendev, @morphizm, @rowanu, @daniilkk, @CacaoRick, @vijayrajasekaran, @mdLn1, @paulwongx, @xwartz, @paulcpro, @AxelBrinck, @imgntn, @CTOlet, @psurma, @gritchou, @joeyenouy007, @primexdev, @Ebi-Tendon, @sarmel, @billyriantono, @teodoraispas, @vitorroliveiraa, @hmborges, @btwotwo, @0x5e5e, @SalmonDaze, @akshayraje, @dogagenc, @youfoundron, @vilyia, @muoi, @Meeken1998, @simonpallister, @alechp, @WilsonWu315, @rmit-s3660109-lorenc-pekaj, @power-jun, @apocoder, @bhram, @HappyOcean, @slinker-hiwa, @davilee103, @gromatluidgi, @ali-master
